### PR TITLE
avcapture: fix macos 10.15 devicesWithMediaType deprecation warning

### LINKED ISSUE #1336: avcapture: warnings on OSX 10.15
```
OC [M]  build-x86_64/modules/avcapture/avcapture.o
modules/avcapture/avcapture.m:154:31: warning: 'devicesWithMediaType:' is
      deprecated: first deprecated in macOS 10.15 - Use
      AVCaptureDeviceDiscoverySession instead. [-Wdeprecated-declarations]
        for (dev in [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo]) {
                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:103:1: note: 
      'devicesWithMediaType:' has been explicitly marked deprecated here
+ (NSArray<AVCaptureDevice *> *)devicesWithMediaType:(AVMediaType)mediaT...
^
modules/avcapture/avcapture.m:381:31: warning: 'devicesWithMediaType:' is
      deprecated: first deprecated in macOS 10.15 - Use
      AVCaptureDeviceDiscoverySession instead. [-Wdeprecated-declarations]
        for (dev in [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo]) {
                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:103:1: note: 
      'devicesWithMediaType:' has been explicitly marked deprecated here
+ (NSArray<AVCaptureDevice *> *)devicesWithMediaType:(AVMediaType)mediaT...
^
2 warnings generated.
```

### PR DESCRIPTION
**Pull request by sreimers**
fixes #1336

### CODE REVIEW

File: modules/avcapture/avcapture.m [hunk 1]
```diff
@@ -150,8 +150,22 @@ + (AVCaptureDevicePosition)get_position:(const char *)name
...
+     __MAC_OS_X_VERSION_MIN_REQUIRED >= 101500)
+	AVCaptureDeviceDiscoverySession *discoverySession;
+
+	discoverySession = [
+		AVCaptureDeviceDiscoverySession
+		discoverySessionWithDeviceTypes:
+			@[AVCaptureDeviceTypeBuiltInWideAngleCamera,
+			  AVCaptureDeviceTypeExternalUnknown]
+		mediaType:AVMediaTypeVideo
+		position:pos
```
Comment (sreimers) [inline modules/avcapture/avcapture.m:163]: I dont know how to test `position` on macOS. Maybe someone can check this on iOS.

**Comment by alfredh** [comment]
great, thanks!
